<?php require(PROJECT_DIR . '/controller/module/header.php'); ?>
  <div class="error-nsfw">
    <div class="container">
      <div class="row pt-5 pb-5">
        <div class="col-lg-3 col-sm-12"></div>
        <div class="col-lg-9 col-12 text-center text-secondary">
          <i class="material-icons text-secondary pt-2 pb-2">visibility_off</i>
          <div class="text-secondary text-uppercase pt-1 pb-1"><?php echo _('Content for adults or prohibited by law in your country'); ?></div>
          <small class="text-secondary pt-2 pb-2"><?php echo _('Item could not be shown in the Safe mode.'); ?></small>
        </div>
      </div>
    </div>
  </div>
<?php require(PROJECT_DIR . '/controller/module/footer.php'); ?>
