<?php require(PROJECT_DIR . '/controller/module/header.php'); ?>
<div class="search-listing">
  <div class="container mt-3 mb-3">
    <div class="row">
      <div class="col-lg-3 col-sm-12"></div>
      <div class="col-lg-9 col-sm-12" id="searchListingContainer">
        <div id="searchListingLoading" class="text-center pt-5 pb-5 d-none">
          <div class="spinner-grow text-primary" role="status">
            <span class="sr-only"><?php echo _('Loading...'); ?></span>
          </div>
        </div>
        <div id="searchListingData"></div>
        <div class="text-center">
          <div id="searchListingLoad" class="btn btn-primary mt-2 mb-2 d-none w-100" onclick="Search.listing.load('#searchListingData', '#searchListingLoad', false)">
            <?php echo _('Show more'); ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php require(PROJECT_DIR . '/controller/module/footer.php'); ?>
